#!/usr/bin/env bash
set -e # halt script on error

git clone https://github.com/pietromenna/jekyll-cayman-theme.git
cd jekyll-cayman-theme
bundle install

bundle exec jekyll build
bundle exec htmlproofer ./_site